version: '3.8'

services:
  kryptokrona-service:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-service
    command: >
      /bin/sh -c " ./src/kryptokrona-service"
    ports:
      - "8070:8070"
    networks:
      xkrnet:
        ipv4_address: 172.10.1.1

  kryptokrona-walletapi:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-walletapi
    command: >
      /bin/sh -c " ./src/wallet-api"
    ports:
      - "5000:5000"
    networks:
      xkrnet:
        ipv4_address: 172.10.1.2

networks:
  xkrnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.10.1.0/16"