version: '3.8'

# not done yet
services:
#  kryptokrona-service:
#    image: ghcr.io/kryptokrona/kryptokrona-testnet
#    container_name: kryptokrona-service
#    command: >
#      /bin/sh -c " ./src/kryptokrona-service"
#    ports:
#      - "8070:8070"
#    networks:
#      - xkrnet

  kryptokrona-walletapi:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-walletapi
    command: >
      /bin/sh -c "python3 walletapi_docker_wrapper.py"
    ports:
      - "8070:8070"
    networks:
      - xkrnet

networks:
  xkrnet:
    driver: bridge